
BEGIN;-- Create a new database
CREATE DATABASE prisma;

-- Create the "user" table
CREATE TABLE customer (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50),
  email VARCHAR(100)
);

-- Create the "invoice" table
CREATE TABLE invoice (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id INT REFERENCES customer(id),
  invoice_date DATE,
  amount DECIMAL(10, 2)
);

-- Populate the "user" table with mock data
INSERT INTO customer ( username, email)
VALUES
  ('user1', 'user1@example.com'),
  ('user2', 'user2@example.com'),
  ('user3', 'user3@example.com'),
  ('user4', 'user4@example.com'),
  ('user5', 'user5@example.com'),
  ('user6', 'user6@example.com'),
  ('user7', 'user7@example.com'),
  ('user8', 'user8@example.com'),
  ('user9', 'user9@example.com'),
  ('user10', 'user10@example.com');

-- Populate the "invoice" table with mock data
INSERT INTO invoice ( customer_id, invoice_date, amount)
VALUES
  ( 1, '2023-01-01', 100.00),
  ( 1, '2023-02-01', 150.00),
  ( 2, '2023-01-15', 75.50),
  ( 2, '2023-02-15', 120.25),
  ( 3, '2023-01-10', 200.00),
  ( 3, '2023-02-10', 75.00),
  ( 4, '2023-01-05', 50.75),
  ( 4, '2023-02-05', 180.00),
  ( 5, '2023-01-20', 95.25),
  ( 5, '2023-02-20', 125.75);

